### PR TITLE
Sign In & Sign Up bug fixes 21,30 enhancement 03

### PR DESCRIPTION
**Pull request by JuanPabloArequipa**
## Bug Fixing:
BUG - ID - 21 - Email Case Sensitivity Issue During Sign In [ [LINK](https://app.clickup.com/t/8686h0ke9) ]
BUG - ID - 30 - Incorrect Success Message After Successful Sign-In [ [LINK](https://app.clickup.com/t/8686jkv13) ]

## Enhancements:
Enhancement - ID - 03 - Add Loader to Sign-In Page [[LINK](https://app.clickup.com/t/8686jkx68) ]

## Reviewers:
@aguirrekarina 
@JeferssonCL

### CODE REVIEW

**Comment by JorgeHB69** [comment]
Task linked: [CU-8686ff86z ID-6.4: Deployment & integration of the sign in view with the backend](https://app.clickup.com/t/8686ff86z)

**Comment by JuanPabloArequipa** [comment]
Task linked: [CU-8686jkv13 BUG - ID - 30 - Incorrect Success Message After Successful Sign-In

](https://app.clickup.com/t/8686jkv13)

**Comment by JuanPabloArequipa** [comment]
Task linked: [CU-8686jkx68 Enhancement - ID - 03 - Add Loader to Sign-In Page](https://app.clickup.com/t/8686jkx68)

**Review by aguirrekarina — APPROVED** [review]
no comments

**Review by DiegoFigueroaSevillano — APPROVED** [review]

**Pull request merged**
