### PR TITLE
Bug ID-12 Responsive design bug filter button overlaps with modal on cellphones

### PR DESCRIPTION
**Pull request by JorgeHB69**
**What?**
Bug fixing of:
https://app.clickup.com/t/8686kerbu
About responsive design overlaps the filter button.

**How?**
Set the filter button with an position absolute.
And manage the alignment in the respective size screen.

**Why?**
Because this improves the UX.

**Reviewers**
@SamuelEscalera 
@aguirrekarina

### CODE REVIEW

**Comment by JorgeHB69** [comment]
Task linked: [CU-8686kerbu Bug id-12 - Responsive Design Bug: Filter Button Overlaps with Modal on Cellphones](https://app.clickup.com/t/8686kerbu)

**Comment by SamuelEscalera** [comment]
image
image



When use a phone size, the filter section overlap the first product

**Comment by SamuelEscalera** [comment]
image


If I deploy a drop down, like brands, I also cover the second product.

**Review by SamuelEscalera — APPROVED** [review]

**Review by aguirrekarina — APPROVED** [review]
no comments

**Pull request merged**
